<?php

declare(strict_types=1);

namespace JMac\Testing;

use JMac\Testing\Engine\IdentifiableDouble;
use JMac\Testing\Engine\MethodExpectation;
use JMac\Testing\Engine\ReceivedAssertion;

/**
 * The seven control verbs every ordinary double generated by `Double::for()`
 * actually has at runtime — `Engine\DoubleControlMethods` both uses this as
 * a trait and `implements` it directly, so it's a real, checkable fact, not
 * a docblock-only fiction.
 *
 * Extends `IdentifiableDouble` rather than declaring `__td_identity()`
 * itself: a double generated in `override` mode (see `Double::for()`) can't
 * implement this interface at all — that's exactly the collision `override`
 * routes around — but it still needs a real, checkable identity, which is
 * `OverriddenDouble`'s job to hold onto instead.
 *
 * Exists for static analysis, not a new capability: a trait can't appear in
 * a PHPStan/Psalm intersection type, only an interface can, and
 * `Double::for()`'s return type needs to express "whatever type you
 * asked for, plus these seven methods."
 */
interface DoubleInterface extends IdentifiableDouble
{
    public function expects(string $method): MethodExpectation;

    public function allows(string $method): MethodExpectation;

    public function strict(): static;

    public function passthru(?object $realInstance = null): static;

    public function received(string $method): ReceivedAssertion;

    public function unused(): void;

    public function verify(): void;
}
